# Generated by Django 4.1.5 on 2023-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_ticketdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Role', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Content', models.CharField(blank=True, max_length=150, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
    ]
