# Generated by Django 4.1.5 on 2023-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_activitydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdb',
            name='Rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
