# Generated by Django 4.1.5 on 2023-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_gallerydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
