# Generated by Django 4.1.5 on 2023-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_feedbackdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdb',
            name='Rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
